In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix
from keras.models import Sequential
from keras.layers import Dense

In [2]:
turbine = pd.read_csv("gas_turbines.csv")
turbine

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583   

           CO     NOX  
0      3.1547  82.722  
1      3.2363  82.776  
2      3.2012  82.468  
3      3.1923  82.670  
4      3.2484  82.311  
...       ...     ...  
15034  4.5186  79.559  
15035  4.8470  79.917  
15036  7.9632  90.912  
15037  6.2494  93.227  
15038  4.9816  92.498  

[15039 rows x 11 columns]

In [3]:
turbine.head()

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0  6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1  6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2  6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3  7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4  7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   

       CO     NOX  
0  3.1547  82.722  
1  3.2363  82.776  
2  3.2012  82.468  
3  3.1923  82.670  
4  3.2484  82.311

In [4]:
turbine.shape

(15039, 11)

In [5]:
turbine.dtypes

AT      float64
AP      float64
AH      float64
AFDP    float64
GTEP    float64
TIT     float64
TAT     float64
TEY     float64
CDP     float64
CO      float64
NOX     float64
dtype: object

In [6]:
turbine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15039 entries, 0 to 15038
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      15039 non-null  float64
 1   AP      15039 non-null  float64
 2   AH      15039 non-null  float64
 3   AFDP    15039 non-null  float64
 4   GTEP    15039 non-null  float64
 5   TIT     15039 non-null  float64
 6   TAT     15039 non-null  float64
 7   TEY     15039 non-null  float64
 8   CDP     15039 non-null  float64
 9   CO      15039 non-null  float64
 10  NOX     15039 non-null  float64
dtypes: float64(11)
memory usage: 1.3 MB


In [7]:
turbine.isnull().sum()

AT      0
AP      0
AH      0
AFDP    0
GTEP    0
TIT     0
TAT     0
TEY     0
CDP     0
CO      0
NOX     0
dtype: int64

In [8]:
# As we have to convert the TEY column into categorical column so need to calculate the mean first and then using lambda function categorize that column into 0's and 1's according to the mean
turbine_mean = turbine.TEY.mean()
turbine_mean

134.18846399361655

In [9]:
turbine['performance'] = turbine.TEY.map(lambda x: 1 if x > 134 else 0)

In [10]:
turbine.performance.value_counts()

0    8484
1    6555
Name: performance, dtype: int64

In [11]:
turbine

AT      AP      AH    AFDP    GTEP     TIT     TAT     TEY     CDP  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  114.70  10.605   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  114.72  10.598   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  114.71  10.601   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  114.72  10.606   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  114.72  10.612   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  111.61  10.400   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  111.78  10.433   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  110.19  10.483   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  110.74  10.533   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  111.58  10.583   

           CO     NOX  performance  
0      3.1547  82.722            0  
1      3.2363  82.776            0  
2      3.2012  82.468            0  
3      3.1923  82.670            0  
4      3.2484  82.311            0  
...       ...     ...          ...  
15034  4.5186  79.559            0  
15035  4.8470  79.917            0  
15036  7.9632  90.912            0  
15037  6.2494  93.227            0  
15038  4.9816  92.498            0  

[15039 rows x 12 columns]

In [12]:
turbine.drop(['TEY'], inplace= True, axis =1)

In [13]:
turbine

AT      AP      AH    AFDP    GTEP     TIT     TAT     CDP      CO  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  10.605  3.1547   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  10.598  3.2363   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  10.601  3.2012   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  10.606  3.1923   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  10.612  3.2484   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  10.400  4.5186   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  10.433  4.8470   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  10.483  7.9632   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  10.533  6.2494   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  10.583  4.9816   

          NOX  performance  
0      82.722            0  
1      82.776            0  
2      82.468            0  
3      82.670            0  
4      82.311            0  
...       ...          ...  
15034  79.559            0  
15035  79.917            0  
15036  90.912            0  
15037  93.227            0  
15038  92.498            0  

[15039 rows x 11 columns]

In [14]:
turbine.shape

(15039, 11)

In [15]:
# splitting the data into x and y as input and output

X = turbine.iloc[:,0:10]
Y = turbine.iloc[:,10]

In [16]:
X

AT      AP      AH    AFDP    GTEP     TIT     TAT     CDP      CO  \
0      6.8594  1007.9  96.799  3.5000  19.663  1059.2  550.00  10.605  3.1547   
1      6.7850  1008.4  97.118  3.4998  19.728  1059.3  550.00  10.598  3.2363   
2      6.8977  1008.8  95.939  3.4824  19.779  1059.4  549.87  10.601  3.2012   
3      7.0569  1009.2  95.249  3.4805  19.792  1059.6  549.99  10.606  3.1923   
4      7.3978  1009.7  95.150  3.4976  19.765  1059.7  549.98  10.612  3.2484   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
15034  9.0301  1005.6  98.460  3.5421  19.164  1049.7  546.21  10.400  4.5186   
15035  7.8879  1005.9  99.093  3.5059  19.414  1046.3  543.22  10.433  4.8470   
15036  7.2647  1006.3  99.496  3.4770  19.530  1037.7  537.32  10.483  7.9632   
15037  7.0060  1006.8  99.008  3.4486  19.377  1043.2  541.24  10.533  6.2494   
15038  6.9279  1007.2  97.533  3.4275  19.306  1049.9  545.85  10.583  4.9816   

          NOX  
0      82.722  
1      82.776  
2      82.468  
3      82.670  
4      82.311  
...       ...  
15034  79.559  
15035  79.917  
15036  90.912  
15037  93.227  
15038  92.498  

[15039 rows x 10 columns]

In [17]:
Y

0        0
1        0
2        0
3        0
4        0
        ..
15034    0
15035    0
15036    0
15037    0
15038    0
Name: performance, Length: 15039, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
#splitting the data into training and test dataset

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size= 0.3, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

StandardScaler()

In [23]:
#Now apply the transformations to the data:
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [24]:
from sklearn.neural_network import MLPClassifier

In [26]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30))

In [27]:
mlp.fit(x_train, y_train)

C:\Users\abhis\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(30, 30))

In [28]:
prediction_train = mlp.predict(x_train)
prediction_test = mlp.predict(x_test)

In [29]:
prediction_train

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [30]:
prediction_test

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [31]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,prediction_test))
np.mean(y_test==prediction_test)
np.mean(y_train==prediction_train)

[[2446   94]
 [ 215 1757]]


0.9498432601880877

### Backpropogation

In [32]:
from keras.models import Sequential
from keras.layers import Dense

In [34]:
#create model
model = Sequential()
model.add(Dense(12, input_dim=10, activation= 'relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation= 'sigmoid'))

In [35]:
# Compile model
model.compile(loss= 'binary_crossentropy', optimizer= 'adam', metrics =['accuracy'])

In [36]:
#fit the model
model.fit(X,Y , validation_split= 0.33, epochs=150, batch_size =10)

Epoch 1/150
1008/1008 [==============================] - 1s 897us/step - loss: 2.0065 - accuracy: 0.4222 - val_loss: 1.0481 - val_accuracy: 0.4390
Epoch 2/150
1008/1008 [==============================] - 1s 835us/step - loss: 0.7325 - accuracy: 0.6005 - val_loss: 0.6627 - val_accuracy: 0.5843
Epoch 3/150
1008/1008 [==============================] - 1s 811us/step - loss: 0.5373 - accuracy: 0.7242 - val_loss: 0.5144 - val_accuracy: 0.6943
Epoch 4/150
1008/1008 [==============================] - 1s 777us/step - loss: 0.4549 - accuracy: 0.7631 - val_loss: 0.3803 - val_accuracy: 0.8162
Epoch 5/150
1008/1008 [==============================] - 1s 778us/step - loss: 0.4196 - accuracy: 0.7767 - val_loss: 0.4126 - val_accuracy: 0.7411
Epoch 6/150
1008/1008 [==============================] - 1s 773us/step - loss: 0.3914 - accuracy: 0.7910 - val_loss: 0.3364 - val_accuracy: 0.8390
Epoch 7/150
1008/1008 [==============================] - 1s 840us/step - loss: 0.3864 - accuracy: 0.7896 - val_loss: 0

1008/1008 [==============================] - 1s 829us/step - loss: 0.3221 - accuracy: 0.8282 - val_loss: 0.2545 - val_accuracy: 0.8537
Epoch 57/150
1008/1008 [==============================] - 1s 832us/step - loss: 0.3247 - accuracy: 0.8266 - val_loss: 0.2392 - val_accuracy: 0.8688
Epoch 58/150
1008/1008 [==============================] - 1s 814us/step - loss: 0.3212 - accuracy: 0.8288 - val_loss: 0.2521 - val_accuracy: 0.8541
Epoch 59/150
1008/1008 [==============================] - 1s 834us/step - loss: 0.3292 - accuracy: 0.8242 - val_loss: 0.2572 - val_accuracy: 0.8527
Epoch 60/150
1008/1008 [==============================] - 1s 869us/step - loss: 0.3252 - accuracy: 0.8227 - val_loss: 0.2412 - val_accuracy: 0.9136
Epoch 61/150
1008/1008 [==============================] - 1s 933us/step - loss: 0.3175 - accuracy: 0.8332 - val_loss: 0.2664 - val_accuracy: 0.8501
Epoch 62/150
1008/1008 [==============================] - 1s 823us/step - loss: 0.3228 - accuracy: 0.8270 - val_loss: 0.2530 

1008/1008 [==============================] - 1s 802us/step - loss: 0.3086 - accuracy: 0.8350 - val_loss: 0.2318 - val_accuracy: 0.9142
Epoch 112/150
1008/1008 [==============================] - 1s 814us/step - loss: 0.3130 - accuracy: 0.8356 - val_loss: 0.2417 - val_accuracy: 0.9220
Epoch 113/150
1008/1008 [==============================] - 1s 827us/step - loss: 0.3067 - accuracy: 0.8329 - val_loss: 0.3223 - val_accuracy: 0.8453
Epoch 114/150
1008/1008 [==============================] - 1s 799us/step - loss: 0.3131 - accuracy: 0.8331 - val_loss: 0.3036 - val_accuracy: 0.8465
Epoch 115/150
1008/1008 [==============================] - 1s 827us/step - loss: 0.3092 - accuracy: 0.8395 - val_loss: 0.2320 - val_accuracy: 0.9228
Epoch 116/150
1008/1008 [==============================] - 1s 833us/step - loss: 0.3143 - accuracy: 0.8348 - val_loss: 0.2794 - val_accuracy: 0.7925
Epoch 117/150
1008/1008 [==============================] - 1s 811us/step - loss: 0.3114 - accuracy: 0.8394 - val_loss: 0

In [37]:
#evaluate the model
scores = model.evaluate(X,Y)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

470/470 [==============================] - 0s 509us/step - loss: 0.2889 - accuracy: 0.8734
accuracy: 87.34%
